title: Mpho Mogale
logo: /assets/img/IMG_22672.jpg
description: Data analytics engineer with 10 years experience in using data to drive business value.
show_downloads: false
theme: jekyll-theme-minimal
