title: Mpho Mogale
logo: /assets/img/IMG_22672.jpg
description: Mpho Mogale is an accomplished analytics engineer with 10 years experience in bridging risk management,
business intelligence and data engineering to drive business value.
show_downloads: true
theme: jekyll-theme-minimal
